// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyW731k6vCj3OSwFIQIvYEvf8DtQqqs10',
    appId: '1:27217569399:web:6b815e685b0ad2936c0872',
    messagingSenderId: '27217569399',
    projectId: 'demonotificationsflutter',
    authDomain: 'demonotificationsflutter.firebaseapp.com',
    storageBucket: 'demonotificationsflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhLLpyGEMn-y-HIfnBuiONL9ipAqt71WQ',
    appId: '1:27217569399:android:a87f741b60a59c2b6c0872',
    messagingSenderId: '27217569399',
    projectId: 'demonotificationsflutter',
    storageBucket: 'demonotificationsflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHfqzV_8hHl6ayKZqCIIeqLlHjHBkoy6E',
    appId: '1:27217569399:ios:2a2f715f518bf4446c0872',
    messagingSenderId: '27217569399',
    projectId: 'demonotificationsflutter',
    storageBucket: 'demonotificationsflutter.firebasestorage.app',
    iosBundleId: 'com.example.demoFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHfqzV_8hHl6ayKZqCIIeqLlHjHBkoy6E',
    appId: '1:27217569399:ios:2a2f715f518bf4446c0872',
    messagingSenderId: '27217569399',
    projectId: 'demonotificationsflutter',
    storageBucket: 'demonotificationsflutter.firebasestorage.app',
    iosBundleId: 'com.example.demoFcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyW731k6vCj3OSwFIQIvYEvf8DtQqqs10',
    appId: '1:27217569399:web:cde75bdbae6727956c0872',
    messagingSenderId: '27217569399',
    projectId: 'demonotificationsflutter',
    authDomain: 'demonotificationsflutter.firebaseapp.com',
    storageBucket: 'demonotificationsflutter.firebasestorage.app',
  );
}
